server:
  port: 8090

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  application:
    name: zuul-server

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

zuul:
  routes:
    productos:
      path: /products/**
      serviceId: product-service
      strip-prefix: false
    items:
      path: /items/**
      serviceId: item-service
      strip-prefix: false
    productos-directo:
      path: /api/directo/**
      url: http://product-service:8081
      strip-prefix: false
  ignored-patterns: /eureka/**

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 6000
  eureka:
    enabled: true

logging:
  level:
    com.autos.zuul: DEBUG
    com.netflix.zuul: INFO
